### ISSUE TITLE
the node to be removed is not a child of this node

### ISSUE THREAD

**Issue by esau-morais** [2nthony/vercel-toast#186]
![image](https://github.com/2nthony/vercel-toast/assets/55207584/5f2fcfa8-6966-434e-9834-9b70d99d0d6a)

v1.8.0

**Comment by 2nthony** [comment]
can you use https://stackblitz.com/ to create a repro?

in my case works correctly

**Comment by esau-morais** [comment]
> can you use https://stackblitz.com/ to create a repro?

i'm sorry, i wouldn't get to do that once it is a private project by my company. i'll try to figure it out what could be possible cause and create a repro

**Comment by 2nthony** [comment]
I created a minimal repro here: https://stackblitz.com/edit/vitejs-vite-1ko9ut?file=package.json,src%2FApp.tsx&terminal=dev

not sure that you can edit or not, still, works.

**Comment by esau-morais** [comment]
the only difference we usually use a custom hook that it is reused in many files and display the toast relying on async requests, so it might be the issue, once it is probably not awaiting it to finish

**Comment by 2nthony** [comment]
you remind me that I should add an API like `destroyToast(id)`,

I saw you use React, so try this one https://github.com/emilkowalski/sonner, looks better.

**Comment by esau-morais** [comment]
closing for now as we decide to use another lib, thank yu

**Comment by esau-morais** [comment]
closing for now as we decide to use another lib, thank you
